### ISSUE TITLE
Scrum/Sprint: prioritized work items

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#100]
This issue details a continuously modifiable list of issues being worked on, queued and deferred

# Working on
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/103
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/102
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/33
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/78
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/91
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/96
-

# Queued prioritized
- periodic timeout on CC creation - https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/93
- 
# Queued non-prioritized
-

# Deferred

# closed
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/99
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/98
- https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/97

**Comment by fmichaelobrien** [comment]
# Developer Documentation Drafts

## Environments

```mermaid
graph LR;
    style Landing-Zones fill:#44f,stroke:#f66,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
    %% mapped and documented

    
    
    manual-->sbx
    manual-->dev
    automated-->stg
    automated-->prd
    
 
    dev-->approach.gcp.zone-->procedure/verify
    sbx-->tbd-checklist.gcp.zone-->experiment
    prd-->landing.gcp.zone-->resilient/stable
    stg-->alternate.gcp.zone-->cicd/automated
    gcp.zone-->gcp-domain-zone
   
```

**Comment by shaunmitchellve** [comment]
@fmichaelobrien We are creating some standardization in our issues. Issues should now fall into 1 of these 3 general buckets:

- Enhancements / Feature Request
- Bugs / Bug Fixes
- Support / How to requests

This issue falls into a work tracking document. We ask that you move this to the Scrum Board Project here https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/projects/1

This issue will be closed in the near future and marked `wont fix`.

Thanks!

**Comment by fmichaelobrien** [comment]
Move directly to advanced - defer arete for now - to get into the solution
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/docs/advanced-install.md
