### ISSUE TITLE
[ENHANCEMENT] add an additional template for enhancements to the single [BUG} 

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#109]
**Describe the bug**
Raising an issue is hardcoded to the bug template - we either need permission to use the empty template for enhancement or add a 2nd one
I would also add sections on bug peer/related links and a section for shell content and workarounds

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cartyc** [comment]
Added a new template for Feature Requests this am #115 . Does that address this issue?

**Comment by fmichaelobrien** [comment]
LGTM

For PR/Issue tracking - can we add the issue reference for pull requests
use "#109 - Add feature request issue template"

A bidirectional link will then link the PR and Issue like below
#109

**Comment by cartyc** [comment]
Addressed in pr #115
