### ISSUE TITLE
Verify np allow-ssh-ingress fwl rule not deleted after kpt live apply after commenting it out - update: verified OK with kpt fn render/kpt live apply only

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#214]
comment out line 39 and below
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/landing-zone/environments/nonprod/firewall/firewall.yaml#L39

render and apply the yaml
```
kpt fn render landing-zone
kpt live apply landing-zone --reconcile-timeout=2m --output=table
```

still up
```
michael@cloudshell:~/dev/pdt-oldev/obriensystems (kcc-lz-8597)$ kubectl get gcp  | grep allow-ssh-ingress
computefirewall.compute.cnrm.cloud.google.com/allow-ssh-ingress             11h   True    UpToDate   103m
computefirewall.compute.cnrm.cloud.google.com/allow-ssh-ingress-pr          11h   True    UpToDate   11h
computefirewall.compute.cnrm.cloud.google.com/allow-ssh-ingressp            11h   True    UpToDate   11h
```

<img width="1269" alt="Screen Shot 2022-12-08 at 11 55 09 AM" src="https://user-images.githubusercontent.com/94715080/206514794-ad5ff857-31d1-4fc9-a88e-365c60d04bee.png">

**Comment by obriensystems** [comment]
Do the reverse
uncomment the firewall rul
Verify direct delete of firewall rule will get replaced back by kcc

```
michael@cloudshell:~/dev/pdt-oldev/cloud-quickstart/pubsec-declarative-toolkit/solutions/landing-zone (kcc-lz-8597)$ kubectl delete computefirewall.compute.cnrm.cloud.google.com/allow-ssh-ingress
computefirewall.compute.cnrm.cloud.google.com "allow-ssh-ingress" deleted
```

**Comment by obriensystems** [comment]
A full kpt cycle brings back the firewall rule

```
kpt pkg update
kpt live init landing-zone --namespace config-control --force
kpt fn render landing-zone
kpt live apply landing-zone --reconcile-timeout=2m --output=table
kpt live status
kpt live status landing-zone
computefirewall.compute.cnrm.cloud.google.com/allow-ssh-ingress is Current: Resource is Current
```

<img width="1719" alt="Screen Shot 2022-12-08 at 14 19 39" src="https://user-images.githubusercontent.com/24765473/206547659-7e43e95c-4ef1-412b-bfa6-b58c0e06d1c3.png">



trying the reverse to delete the rule - comment in yaml the full kpt cycle

**Comment by obriensystems** [comment]
with just a fn render and live apply - yes to resource deletion
```
not needed
kpt live init landing-zone --namespace config-control --force

michael@cloudshell:~/dev/pdt-oldev/cloud-quickstart (kcc-lz-8597)$ kpt fn render landing-zone
michael@cloudshell:~/dev/pdt-oldev/cloud-quickstart (kcc-lz-8597)$ kpt live apply landing-zone --reconcile-timeout=2m --output=table
michael@cloudshell:~/dev/pdt-oldev/cloud-quickstart (kcc-lz-8597)$ kpt live status landing-zone
no resources found in the inventory

```
Although this was the 2nd time I attempted the delete via kcc without resorting to kubectl delete
<img width="1328" alt="Screen Shot 2022-12-08 at 14 37 40" src="https://user-images.githubusercontent.com/24765473/206551208-2638e412-afa9-450b-9a54-3938d20a5fb1.png">

**Comment by fmichaelobrien** [comment]
firewall deletion occurred in 35 sec
