### ISSUE TITLE
Fix landing-zone nomos PR validation run

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#219]
Fix landing-zone nomos validation run

The nomos validation runs have been failing on tooling since last week - unrelated to this particular PR - looking into them

https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/actions/runs/3675947600/jobs/6216008018#step:4:53
older
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/actions/runs/3658061679/jobs/6182390338#step:4:52

**Comment by cartyc** [comment]
Thanks for filling the bug! I noticed that the other day but haven't had the chance to debug it yet. Will try to get that fixed before the holidays.

**Comment by fmichaelobrien** [comment]
sounds good, I was planning on triaging the pipeline in the queue - thanks for taking on this one

**Comment by cartyc** [comment]
PR #237 just opened should address this issue.
