### ISSUE TITLE
Logging / Monitoring For Sandbox MVP

### ISSUE THREAD

**Issue by davelanglois-ssc** [GoogleCloudPlatform/pubsec-declarative-toolkit#284]
implement the logging solution for the sandbox landing zone as per agreed design

**Comment by cheffj** [comment]
In scope:
- logging of breakglass account usage
- security logs: audit logs and access transparency logs
- data access logs for the infrastructure managed by the platform admin
- platform and components logs for the infrastructure managed by the platform admin

Out of scope: 
- alerting on breakglass account usage
- data access logs for clients (will be addressed when the work with the pathfinder has started)
