### ISSUE TITLE
Fix depends-on annotation in registry.yaml

### ISSUE THREAD

**Issue by lucstjean-ssc** [GoogleCloudPlatform/pubsec-declarative-toolkit#304]
**Describe the bug**
The depends-on annotation on line #23 in solutions/sandbox-gke/artifact-registry/registry.yaml contains an invalid field.
The API version should not be included.

https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/sandbox-gke/artifact-registry/registry.yaml#L23

```yaml
config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/v1beta1/namespaces/config-control/Service/my-demo-guardrails-controller-services-artifactregistry # kpt-set: serviceusage.cnrm.cloud.google.com/v1beta1/namespaces/${project-namespace}/Service/${project-id}-services-artifactregistry
```

**To Reproduce**
Deploy code as is to reproduce the error.

**Expected behavior**
Successful deployment of the resource.

**Additional context**
`v1beta1` should be removed twice on this line:

```yaml
config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/v1beta1/namespaces/config-control/Service/my-demo-guardrails-controller-services-artifactregistry # kpt-set: serviceusage.cnrm.cloud.google.com/v1beta1/namespaces/${project-namespace}/Service/${project-id}-services-artifactregistry
```

**Comment by cartyc** [comment]
Addressed in PR #332
