### ISSUE TITLE
GKE container errors - Experimentation

### ISSUE THREAD

**Issue by cheffj** [GoogleCloudPlatform/pubsec-declarative-toolkit#328]
**Describe the bug**
GKE container errors - Experimentation

**Screenshots**
![image](https://user-images.githubusercontent.com/102672913/230453708-4cd401be-6af8-419a-9ecd-3729c50a6f68.png)

**Additional context**
More details pulled from the logs.

2023-03-15T14:13:53.753Z        error   exporterhelper/queued_retry.go:149      
Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors      
{"kind": "exporter", "data_type": "metrics", "name": "googlecloud", 
"error": "failed to export time series to GCM: rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist)."}

Either the container is running with the wrong permissions to create the time series (Need to add roles/monitoring.editor) See https://cloud.google.com/monitoring/access-control page.  
Or the resource type that is wants to use is incorrect. See https://cloud.google.com/monitoring/api/resources for the list of monitored resource that are available

**Comment by cartyc** [comment]
@cheffj what is the configuration of the GKE cluster when you bring it up? Think you're right on the permissions issue, might be the initial scopes on the nodes.

**Comment by cartyc** [comment]
Ahh, thanks for the update!

**Comment by cheffj** [comment]
New issue on gke that is racking up another 20,000+ logs/hour. Those excessive logs are being sent to our central log bucket. We're going to implement a temporary filter to stop routing those logs into our central log bucket and cut costs.
