### ISSUE TITLE
fix required on folder/Org IAM permissions

### ISSUE THREAD

**Issue by muneebhussain** [GoogleCloudPlatform/pubsec-declarative-toolkit#331]
**Describe the bug**

Syntax error in folder-iam.yaml . Folder Viewer & Org Viewer permissions are failing due to syntax error . 

Referring to below yaml
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/hierarchy/client-env/folder-iam.yaml
 
I think it should be like this

`  role: roles/resourcemanager.folderViewer
  member: "**serviceAccount:**hierarchy-sa@prj-bootstrap-381413.iam.gserviceaccount.com"`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error Snapshot :**
![EpicPen_GopYzZNExs](https://user-images.githubusercontent.com/17991981/231212286-a4b925b5-3bd2-4380-9ae2-8a3a1dbc1194.png)

**Additional context**

**Comment by cartyc** [comment]
Thanks @muneebhussain ! Looks like you're right it should be either `user:<member>`, `group:<member>` or `serviceaccount:<memeber>` . I'll get a second set of eyes on that as well and get a PR together to fix that.

**Comment by cartyc** [comment]
I just took another look at the package setters file and the default value there is `'group:client1@example.com'` . Are you entering your user in setters or directly in the [folder-iam.yaml](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/hierarchy/client-env/folder-iam.yaml) yaml?

**Comment by muneebhussain** [comment]
I apologize for the confusion. I just realized that my local repository was not up-to-date with the latest changes. I see that the syntax has been updated correctly in the latest version.

**Comment by cartyc** [comment]
No worries, thanks for opening the issue and letting us know!
