### ISSUE TITLE
Landing Zone V2 alignment to V1 or TEF V4

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/pubsec-declarative-toolkit#621]
see ongoing work to get a terraform version of the public sector GCP landing zone in

https://github.com/terraform-google-modules/terraform-example-foundation/issues/1133

https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues
https://github.com/terraform-google-modules/terraform-example-foundation/issues/940
https://github.com/CloudLandingZone/cloud-foundation-fabric/tree/master/fast
https://github.com/GoogleCloudPlatform/professional-services/tree/main/examples
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/config-connector/solutions
https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/modules

**Comment by fmichaelobrien** [comment]
duplicates https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/360
