### ISSUE TITLE
fix: specify that log sinks are enabled

### ISSUE THREAD

**Issue by alaincormier-ssc** [GoogleCloudPlatform/pubsec-declarative-toolkit#687]
the current YAML manifests for `kind: LoggingLogSink` rely on [undocumented](https://cloud.google.com/config-connector/docs/reference/resource-docs/logging/logginglogsink) default of `spec.disabled: false` to be enabled.

this can cause undesired results when running a test/development landing zone, for example:
1. adding `spec.disabled: true` during testing to minimize cost
2. removing `spec.disabled: true` to test a logging specific feature

Result: the spec observed does not properly update and the sink remains disabled.

To avoid any issues and ambiguity, the `spec.disabled` field should always be present.  This will also make it easier in the future to run a find/replace mutator during testing.

**Comment by fmichaelobrien** [comment]
@alaincormier-ssc , thank you for the heads up on the spec.disabled field at https://cloud.google.com/config-connector/docs/reference/resource-docs/logging/logginglogsink#custom_resource_definition_properties - we have several other sinks including ones to pubsub for log export and your research is greatly appreciated
