### ISSUE TITLE
Fix problematic commands used in the landing zone v2 readme doc

### ISSUE THREAD

**Issue by jacyang2010** [GoogleCloudPlatform/pubsec-declarative-toolkit#739]
**Describe the bug**
Some commands used in the readme.md are incorrect as shown below:
- kubectl delete root-sync landing-zone -n config-management-system
- kubectl delete gcp --all

**To Reproduce**
Run the doc and you will see the above two commands doesn't work as expected.

**Expected behavior**

No any command error and all gcp resources are removed.

**Screenshots**
None

**Additional context**
None

**Comment by fmichaelobrien** [comment]
Related - https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/593
