### ISSUE TITLE
As a developer I wish to have a local Golang environment up to build arete (Google Cloud Shell is GO ready)

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#80]
In the arete documentation as part of the overall pubsec-declarative-toolkit install we require Golang setup and configured.
Currently the Google Cloud Shell is good to go at https://shell.cloud.google.com/
This adjustment to the readme below should add a go install link or procedure for local gcloud users (local laptops)
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/cli/README.md

todo: document several approaches to getting go locally (osx/darwin, jetbrains, docker) - see http://wiki.obrienlabs.cloud/display/DEV/Go+Lang+Developer+Guide

see install references in the onboarding task https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/33#issuecomment-1230392181

As Chris mentioned - a download option should be added as well

**Comment by cartyc** [comment]
Updated documentation and merged with PR #81 .
