### ISSUE TITLE
Add HA Fortigate as a Solution or Service

### ISSUE THREAD

**Issue by cartyc** [GoogleCloudPlatform/pubsec-declarative-toolkit#84]
Some implementations of the Landing Zone will require a fortigate appliance and in order to provide that functionality we should have either a service or solution we can distribute as a standalone or package with the LZ as needed.

The reference terraform module is located [here](https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/fortigate-appliance).

This would need to be converted into the Config Connector format in order to keep in line with the goal of keeping the LZs at parity.

**Comment by fmichaelobrien** [comment]
Coordination with https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/45

**Comment by fmichaelobrien** [comment]
Link to fortigate issues above
#168
#166 
#162

**Comment by cartyc** [comment]
See PR's #283 and #305
