### ISSUE TITLE
LZ infra HA active/standby: As an Org Admin I need to modify the Landing Zone shared infrastructure via promotion of the staging side of a dual prod/stg - in eviction scenarios

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#89]
# use case: landing zone shared infrastructure needs an upgrade that meets the threashold of workload eviction - we need an HA configuration that uses a staging or standby perimeter/management/
Note: most changes may be non-global atomic like changing firewall rules
Note: migrating workload projects under subfolders is also a separate work item depending on whether the test environment can be used for staging

Collaboration: https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/165

**Comment by cartyc** [comment]
Clarifying question, are we talking about running two LZs (dev/prod) in parallel in the same organization to be able to catch any changes that could cause a delete and replace event (ie destroy and recreate a VPC) or just different environments via project/folder structure?

**Comment by cartyc** [comment]
Agree leveraging namespaces for this would be ideal. Shaun already put together a solution for this [here](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/kcc-namespaces) which is based off the following docs for running multi-tenancy with project scoped namespaces https://cloud.google.com/anthos-config-management/docs/tutorials/project-namespace-blueprint .
