### ISSUE TITLE
As a developer I need a single node GKE cluster down from the default 3 as part of overall FinOps cost reduction for the anthos config controller

### ISSUE THREAD

**Issue by fmichaelobrien** [GoogleCloudPlatform/pubsec-declarative-toolkit#90]
Use case: we should be able to run the master and worker nodes on one single VM (8g I hope) - I know this defeats replicaset scaling and HA but this will reduce the cost from by close to 1/3 to keep the K8S cluster up.

The anthos config controller has a 2 part fee schedule - anthos/hr and the gke /hr. Both defaulting to .1
https://cloud.google.com/anthos-config-management/docs/pricing

Something like using Chris's private GKE cluster solution of 1 - as the KCC cluster itself
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/services/private-gke/setters.yaml#L49

Finding the values/setters yaml override for use by arete

checking
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/sandbox-gke/private-gke/gke/containernodepool.yaml#L27

Arete values.yaml generated or use the non arete advanced manual install

**Comment by cartyc** [comment]
Unfortunately I don't believe the cluster sizing is configurable as part of the Config Controller APIs. Agree it would be good to keep the sizing minimal but I trust there is a reason it was designed this way.

If a minimal node setup were to be required the Config Connector, Config Management and Policy Controller components that make up Config Controller could be installed on a GKE or CNCF conformant Kubernetes cluster of your the clients choosing.  This would come at the cost of the client needing to manage the components in additional to the KCC configs.

**Comment by fmichaelobrien** [comment]
Rereading my first GCP LZ deployment https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone - yes looks like an atomic operation for now.
```
gcloud anthos config controller create ${CONFIG_CONTROLLER_NAME} --location=${REGION}
```  
I still have Rancher 1.6/2.0 single node clusters in my brain

**Comment by cartyc** [comment]
I will keep tabs on this and if anything changes with how the underlying clusters get created I will update this issue. Closing for now as there is not much we can do to change that behavior.

**Comment by fmichaelobrien** [comment]
I recommend we keep it open with at least a mitigation to pause)delete the cc cluster until we can resize it.  For a developer instance we don't need a full ha 3 node cluster.  I would recommend an offline ode for the deployment where we need an initial lz deploy but don't need the k8s intent framework tracking changes.  I will look more into this.

**Comment by cartyc** [comment]
Options for that would be either [kind](https://kind.sigs.k8s.io/) or [minikube](https://minikube.sigs.k8s.io/docs/start/). This would require installing all of the components locally which could increase complexity but is still a viable option. For example here's the install guide for [config connector](https://cloud.google.com/config-connector/docs/how-to/install-other-kubernetes).

The biggest appeal in my opinion is having the continuous reconciliation running which would require the CC instance running at all times. For a dev environment or testing I think bringing it up and down would be alright but for production workloads I wouldn't recommend that approach as you could end up missing any config changes/drift. 

I did a test this morning on this topic. You can delete the CC instance without destroying the objects it is watching and redeploy a new instance with the same configs and it will re-acquire them. So this should work for local deploys using the K8S deployment of your choice.

**Comment by fmichaelobrien** [comment]
Reviewing 
https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#setting_up

**Comment by obriensystems** [comment]
Testing out reducing the node pool from 3 zones to 1 for a minimum dev cluster - 26% saturation - most nodes coming up
regression testing will need the LZ deployed - see
#99 

```
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit/landing-zone (landing-zone-controller-1z583)$ kubectl get nodes -o wide
NAME                                                  STATUS   ROLES    AGE     VERSION            INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gke-krmapihost-landi-krmapihost-landi-7d75b5c9-bxqq   Ready    <none>   3h13m   v1.22.11-gke.400   192.168.0.7   <none>        Container-Optimized OS from Google   5.10.109+        containerd://1.5.13
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit/landing-zone (landing-zone-controller-1z583)$ kubectl get pods --all-namespaces
NAMESPACE                         NAME                                                             READY   STATUS              RESTARTS       AGE
cnrm-system                       cnrm-controller-manager-ccd8mhcgkgtdktv36t6g-0                   0/2     Pending             0              1s
cnrm-system                       cnrm-deletiondefender-0                                          0/1     Pending             0              1s
cnrm-system                       cnrm-resource-stats-recorder-7d49746fc6-rv7n4                    0/2     ContainerCreating   0              1s
cnrm-system                       cnrm-webhook-manager-85f4848bc4-bpw42                            0/1     Pending             0              1s
cnrm-system                       cnrm-webhook-manager-85f4848bc4-p2psg                            1/1     Running             0              3h12m
config-management-monitoring      otel-collector-5d9757b898-gnzfv                                  0/1     Pending             0              1s
config-management-system          config-management-operator-64ff79d555-cpnnd                      0/1     ContainerCreating   0              1s
config-management-system          reconciler-manager-6c5967d99b-sjjs6                              0/2     Pending             0              1s
configconnector-operator-system   configconnector-operator-0                                       0/1     ContainerCreating   0              1s
gatekeeper-system                 gatekeeper-audit-68fb44f5bc-ftpcc                                1/1     Running             0              3h12m
gatekeeper-system                 gatekeeper-controller-manager-5d768f8f49-8v9jj                   1/1     Running             0              4m47s
krmapihosting-monitoring          krmapihosting-metrics-agent-n7wkw                                1/1     Running             0              3h12m
krmapihosting-system              bootstrap-5ffd94d5cd-7xpml                                       1/1     Running             3 (3h7m ago)   3h13m
kube-system                       event-exporter-gke-5479fd58c8-c4bqz                              2/2     Running             0              4m48s
kube-system                       fluentbit-gke-48cmq                                              2/2     Running             0              3h13m
kube-system                       gke-metadata-server-st8s7                                        1/1     Running             0              3h13m
kube-system                       gke-metrics-agent-v8bd5                                          1/1     Running             0              3h13m
kube-system                       kube-dns-85df8994db-99rct                                        4/4     Running             0              4m48s
kube-system                       kube-dns-autoscaler-f4d55555-q7s8k                               1/1     Running             0              4m48s
kube-system                       kube-proxy-gke-krmapihost-landi-krmapihost-landi-7d75b5c9-bxqq   1/1     Running             0              3h13m
kube-system                       l7-default-backend-69fb9fd9f9-b8kj5                              1/1     Running             0              4m48s
kube-system                       metrics-server-v0.4.5-fb4c49dd6-6lrtq                            2/2     Running             0              4m48s
kube-system                       netd-7q2xz                                                       1/1     Running             0              3h13m
kube-system                       pdcsi-node-bw2fz                                                 2/2     Running             0              3h13m
resource-group-system             resource-group-controller-manager-6c6774ff66-9ktnm               3/3     Running             0              3h12m
michael@cloudshell:~/github/GoogleCloudPlatform/pubsec-declarative-toolkit/landing-zone (landing-zone-controller-1z583)$ kubectl top nodes
NAME                                                  CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-krmapihost-landi-krmapihost-landi-7d75b5c9-bxqq   1531m        79%    1583Mi          26%
```

<img width="857" alt="Screen Shot 2022-09-08 at 23 47 20" src="https://user-images.githubusercontent.com/24765473/189268616-fcd54399-232c-4bf2-85d5-492775b96d5b.png">

<img width="1674" alt="Screen Shot 2022-09-08 at 23 47 59" src="https://user-images.githubusercontent.com/24765473/189268627-c78bae73-71de-4901-8006-b49a8a4d1a5c.png">

<img width="1673" alt="Screen Shot 2022-09-08 at 23 51 46" src="https://user-images.githubusercontent.com/24765473/189268634-6deea603-e087-42ed-8167-b2e5a9771b14.png">

**Comment by cartyc** [comment]
Official documentation states that we should not be modifying the cluster on the backend as it could cause irreparable damage to the instance. "Warning: Do not use the [GKE API](https://cloud.google.com/kubernetes-engine/docs/reference/rest) or the associated [Google Cloud CLI commands](https://cloud.google.com/sdk/gcloud/reference/container/clusters/update) to modify the cluster that backs your Config Controller instance. Doing so can cause irreparable damage and you might need to delete and then recreate the instance."

I think this is something we need to take back and discuss internally as we don't have the knobs to turn to modify what is created.

**Comment by fmichaelobrien** [comment]
Chris, makes sense as the config tooling above gke in anthos might unsync.  I would need to force 1 node anyway as we periodically hit scaling to 2.

And honestly after running this I don't want to bring in any chance of functional timeouts forcing replica sets on a single node

**Comment by cartyc** [comment]
Alpha support for autopilot based Instances `gcloud alpha anthos config controller create --full-management`

**Comment by fmichaelobrien** [comment]
Very nice - should be half cost
```
michael@cloudshell:~ (biometric-dev)$ gcloud alpha anthos config controller create --full-management test --location northamerica-northeast1
Create request issued for: [test]
Waiting for operation [projects/biometric-dev/locations/northamerica-northeast1/operations/operation-1662737594059-5e84043a60bed-f04accb6-06151453] to complete...done.     
Created instance [test].
Fetching cluster endpoint and auth data.
kubeconfig entry generated for krmapihost-test.

4+1 nodes under the covers
michael@cloudshell:~ (biometric-dev)$ kubectl top nodes
NAME                                             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gk3-krmapihost-test-default-pool-1bf31e9b-n1qn   126m         13%    1290Mi          45%
gk3-krmapihost-test-default-pool-1bf31e9b-q78g   86m          9%     1036Mi          36%
gk3-krmapihost-test-default-pool-1df6d6c4-bbkv   103m         10%    1451Mi          51%
gk3-krmapihost-test-default-pool-1df6d6c4-w2jq   194m         20%    1053Mi          37%
gk3-krmapihost-test-nap-l3jpbylo-09984847-d4dz   107m         5%     1226Mi          20%

michael@cloudshell:~ (anthos-ol)$ kubectl get nodes -o wide
NAME                                             STATUS   ROLES    AGE   VERSION            INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gk3-krmapihost-test-default-pool-39c3c1b5-7wm7   Ready    <none>   19m   v1.22.11-gke.400   10.162.0.3    <none>        Container-Optimized OS from Google   5.10.109+        containerd://1.5.13
gk3-krmapihost-test-default-pool-39c3c1b5-8lx7   Ready    <none>   15m   v1.22.11-gke.400   10.162.0.5    <none>        Container-Optimized OS from Google   5.10.109+        containerd://1.5.13
gk3-krmapihost-test-default-pool-39c3c1b5-dpkv   Ready    <none>   15m   v1.22.11-gke.400   10.162.0.6    <none>        Container-Optimized OS from Google   5.10.109+        containerd://1.5.13
gk3-krmapihost-test-default-pool-9f318add-hv7s   Ready    <none>   19m   v1.22.11-gke.400   10.162.0.2    <none>        Container-Optimized OS from Google   5.10.109+        containerd://1.5.13
gk3-krmapihost-test-nap-2nk1e3x7-8495bbf5-jr8z   Ready    <none>   14m   v1.22.11-gke.400   10.162.0.7    <none>        Container-Optimized OS from Google   5.10.109+        containerd://1.5.13
```
<img width="1510" alt="Screen Shot 2022-09-09 at 12 02 47 PM" src="https://user-images.githubusercontent.com/94715080/189393501-1aa616e3-514b-4f00-a389-52d005772c4e.png">
